name: Build Visual Studio Project

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug,Release]
    name: Build (${{ matrix.Configuration }})
    needs: new-release
    runs-on: windows-latest
    env:
      SigningCertificate: "Web Browser_TemporaryKey.pfx"
      Wap_Project_Directory: "Web Browser"
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Decode the Pfx
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
          $currentDirectory = Get-Location
          $certificatePath = Join-Path -Path $currentDirectory -ChildPath $env:Wap_Project_Directory -AdditionalChildPath $env:SigningCertificate
          [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
      - name: Build app for ${{ matrix.Configuration }}
        run: msbuild "Web Browser.sln" /property:Configuration=${{ matrix.Configuration }}
      - name: Remove the .pfx
        run: Remove-Item -path $env:Wap_Project_Directory/$env:SigningCertificate
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.new-release.outputs.upload_url }}
          asset_path: ./Web Browser/bin/${{ matrix.Configuration }}/Web Browser.exe
          asset_name: Web Browser (${{ matrix.Configuration }}).exe
          asset_content_type: application/octet-stream
  new-release:
    runs-on: windows-latest
    name: Create new release
    outputs:
     upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get current time with dashes
        uses: 1466587594/get-current-time@v2
        id: current_time_dashes
        with:
          format: YYYY-MM-DD
      - name: Get current time with underscores
        uses: 1466587594/get-current-time@v2
        id: current_time_underscores
        with:
          format: YYYY_MM_DD
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           tag_name: ${{ steps.current_time_dashes.outputs.formattedTime }}-${{ GITHUB.RUN_NUMBER }}-${{ GITHUB.RUN_ID }}
           release_name: ${{ steps.current_time_dashes.outputs.formattedTime }}
